// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieHub.API.DbContexts;

#nullable disable

namespace MovieHub.API.Migrations
{
    [DbContext(typeof(MovieHubDbContext))]
    [Migration("20240701003607_AddedTableMovieReview")]
    partial class AddedTableMovieReview
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("MovieHub.API.Entities.Cinema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Cinema");
                });

            modelBuilder.Entity("MovieHub.API.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("director");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("genre");

                    b.Property<string>("PrincessTheatreMovieId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("princessTheatreMovieId");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT")
                        .HasColumnName("rating");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("releaseDate");

                    b.Property<int>("Runtime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("runtime");

                    b.Property<string>("Synopsis")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("synopsis");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("Movie");
                });

            modelBuilder.Entity("MovieHub.API.Entities.MovieCinema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateOnly>("Showtime")
                        .HasColumnType("TEXT")
                        .HasColumnName("showtime");

                    b.Property<decimal>("TicketPrice")
                        .HasColumnType("TEXT")
                        .HasColumnName("ticketPrice");

                    b.Property<int>("cinemaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("movieId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("cinemaId");

                    b.HasIndex("movieId");

                    b.ToTable("MovieCinema");
                });

            modelBuilder.Entity("MovieHub.API.Entities.MovieReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT")
                        .HasColumnName("comment");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("reviewDate");

                    b.Property<decimal>("Score")
                        .HasPrecision(4, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("score");

                    b.Property<int>("movieId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("movieId");

                    b.ToTable("MovieReview");
                });

            modelBuilder.Entity("MovieHub.API.Entities.MovieCinema", b =>
                {
                    b.HasOne("MovieHub.API.Entities.Cinema", "Cinema")
                        .WithMany()
                        .HasForeignKey("cinemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieHub.API.Entities.Movie", "Movie")
                        .WithMany("MovieCinemas")
                        .HasForeignKey("movieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cinema");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieHub.API.Entities.MovieReview", b =>
                {
                    b.HasOne("MovieHub.API.Entities.Movie", "Movie")
                        .WithMany("MovieReviews")
                        .HasForeignKey("movieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieHub.API.Entities.Movie", b =>
                {
                    b.Navigation("MovieCinemas");

                    b.Navigation("MovieReviews");
                });
#pragma warning restore 612, 618
        }
    }
}
